### ISSUE TITLE
Temp files are not deleted

### ISSUE THREAD

**Issue by maierl** [cmci/MultiStackRegistration#7]
Running the plugin in headless mode leaves a lot of temp files in my temp folder, which take the whole disk space after a few hours. My workaround checks for *StackReg* files that are older than 30 minutes and deleting them periodically. It certainly affects windows machines, not sure about Linux.

**Comment by miura** [comment]
HI @maierl 

I made the plugin to delete temp files. [Could you try?](https://github.com/cmci/MultiStackRegistration/releases/tag/v1.46.2)

**Comment by maierl** [comment]
Thanks for your quick help @cmci! The temp files are deleted properly now.
If the plugin uses only 3 files at a time, maybe it only needs to have 3 temp files per process and could overwrite them during execution? Just if harddrive access is actually limiting the plugin's speed.

**Comment by miura** [comment]
Hi @maierl 

Your idea was actually there at some earlier stage and since it causes fatal errors, we modified the code. Please see the following thread. 

http://forum.imagej.net/t/running-multiple-instances-of-imagej/388/4

By the way, are you in DKFZ? I started freelance job so if there is someone with needs for development or collaboration, I can do that professionally so please spread. 

Cheers, 
Kota

**Comment by maierl** [comment]
Hmm, ok. What I meant is that it needs a unique name per process / instance, but not per slice. Would that make sense to you?

And yes, I'm in Christian's group at DKFZ, just forwarded your news :)
